//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opserver.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Snapshot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Snapshot()
        {
            this.SnapshotNodes = new HashSet<SnapshotNode>();
        }
    
        public int SnapshotID { get; set; }
        public Nullable<int> BatchRequestsSec { get; set; }
        public Nullable<int> SQLCompilationsSec { get; set; }
        public Nullable<int> TransactionsSec { get; set; }
        public Nullable<int> IndexSearchesSec { get; set; }
        public Nullable<int> LockRequestsSec { get; set; }
        public Nullable<int> ErrorsSec { get; set; }
        public Nullable<int> CPU { get; set; }
        public Nullable<int> RAM { get; set; }
        public Nullable<int> Connections { get; set; }
        public Nullable<int> Sessions { get; set; }
        public Nullable<int> MaxWorkers { get; set; }
        public Nullable<int> TotalServerMemory { get; set; }
        public Nullable<int> TargetServerMemory { get; set; }
        public Nullable<int> DatabaseCacheMemory { get; set; }
        public Nullable<int> FreeMemory { get; set; }
        public Nullable<int> DataFilesSize { get; set; }
        public Nullable<int> LogFileSize { get; set; }
        public Nullable<int> LogFileUsedSize { get; set; }
        public Nullable<int> FreeSpaceinTempDB { get; set; }
        public Nullable<int> PageLifeExpectancy { get; set; }
        public Nullable<int> PageLookupsSec { get; set; }
        public Nullable<int> DatabasePages { get; set; }
        public Nullable<int> ObjectsInCache { get; set; }
        public Nullable<double> CacheHitRatio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SnapshotNode> SnapshotNodes { get; set; }
    }
}
