//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opserver.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SnapshotNode
    {
        public int SnapshotCounter { get; set; }
        public int SnapshotID { get; set; }
        public int NodeID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Node Node { get; set; }
        public virtual Snapshot Snapshot { get; set; }
    }
}
